-- MySQL Script generated by MySQL Workbench
-- Wed Jan  3 17:12:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema igt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema igt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `igt` DEFAULT CHARACTER SET utf8 ;
USE `igt` ;

-- -----------------------------------------------------
-- Table `igt`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igt`.`Company` ;

CREATE TABLE IF NOT EXISTS `igt`.`Company` (
  `company_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `house number` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `post code` INT NULL,
  `place` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `owner_name` VARCHAR(45) NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igt`.`Warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igt`.`Warehouse` ;

CREATE TABLE IF NOT EXISTS `igt`.`Warehouse` (
  `warehouse_id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `post code` INT NULL,
  `place` VARCHAR(45) NULL,
  `house number` VARCHAR(45) NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`warehouse_id`),
  INDEX `company_id_idx` (`company_id` ASC),
  CONSTRAINT `company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `igt`.`Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igt`.`District`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igt`.`District` ;

CREATE TABLE IF NOT EXISTS `igt`.`District` (
  `district_id` INT NOT NULL,
  `warehouse_id` INT NOT NULL,
  PRIMARY KEY (`district_id`),
  INDEX `warehouse_id_idx` (`warehouse_id` ASC),
  CONSTRAINT `warehouse_id`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `igt`.`Warehouse` (`warehouse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igt`.`Adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igt`.`Adress` ;

CREATE TABLE IF NOT EXISTS `igt`.`Adress` (
  `district_id` INT NOT NULL,
  `adress_id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `house number` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `post code` INT NULL,
  `place` VARCHAR(45) NULL,
  PRIMARY KEY (`adress_id`),
  INDEX `district_id_idx` (`district_id` ASC),
  UNIQUE INDEX `adress_id_UNIQUE` (`adress_id` ASC),
  CONSTRAINT `district_id`
    FOREIGN KEY (`district_id`)
    REFERENCES `igt`.`District` (`district_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igt`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igt`.`Customer` ;

CREATE TABLE IF NOT EXISTS `igt`.`Customer` (
  `customer_id` INT NOT NULL,
  `adress_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `b_date` DATE NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC),
  INDEX `adress_id_idx` (`adress_id` ASC),
  CONSTRAINT `adress_id`
    FOREIGN KEY (`adress_id`)
    REFERENCES `igt`.`Adress` (`adress_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igt`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igt`.`Order` ;

CREATE TABLE IF NOT EXISTS `igt`.`Order` (
  `order_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `amount` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `igt`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igt`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igt`.`Item` ;

CREATE TABLE IF NOT EXISTS `igt`.`Item` (
  `item_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `producer` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`item_id`),
  INDEX `order_id_idx` (`order_id` ASC),
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `igt`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
